<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Contracts\IPostComment.cs" />
    <Compile Remove="Implementations\PostCommentRepository.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tetas.Common\Tetas.Common.csproj" />
    <ProjectReference Include="..\Tetas.Domain\Tetas.Domain.csproj" />
    <ProjectReference Include="..\Tetas.Infraestructure\Tetas.Infraestructure.csproj" />
  </ItemGroup>

</Project>
